name: Deploy to Google App Engine

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to App Engine
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY_FILE }}
          gcloud app deploy app.yaml --quiet